create extension if not exists pgcrypto;

insert into storage.buckets (id, name, public)
values ('documents', 'documents', false)
on conflict (id) do update set public = false;

create table if not exists public.documents (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null check (char_length(title) between 1 and 120),
  original_name text not null,
  storage_path text not null unique,
  mime_type text not null default 'application/octet-stream',
  size_bytes bigint not null check (size_bytes > 0),
  password_hash text,
  access_password text check (access_password is null or char_length(access_password) between 6 and 64),
  download_start timestamptz,
  download_end timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint valid_download_window check (download_end > download_start)
);

create index if not exists documents_slug_active_idx
on public.documents (slug, active);

create table if not exists public.download_attempts (
  id bigint generated by default as identity primary key,
  document_id uuid not null references public.documents(id) on delete cascade,
  ip_hash text not null,
  success boolean not null default false,
  attempted_at timestamptz not null default now()
);

create index if not exists download_attempts_rate_limit_idx
on public.download_attempts (document_id, ip_hash, attempted_at desc);

alter table public.documents enable row level security;
alter table public.download_attempts enable row level security;

-- Support databases created before plaintext passwords were introduced.
alter table public.documents add column if not exists access_password text;
alter table public.documents alter column password_hash drop not null;
alter table public.documents alter column download_start drop not null;
alter table public.documents alter column download_end drop not null;

-- Không tạo policy public. Mọi thao tác database/storage đều đi qua
-- Next.js server bằng secret/service-role key; bucket "documents" luôn private.
